### ISSUE TITLE
Build error on manylinux_2_28_x64 with GCC 12.1.1

### ISSUE THREAD

**Issue by dzenanz** [google/tensorstore#69]
This happens with the latest version, efca7ed88fcdc6e2a64bdb12626cdaeb92b92ecb.
```log
...
[811/2057] Building C object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/compress/zstdmt_compress.c.o
[812/2057] Building C object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/compress/zstd_opt.c.o
[813/2057] Building ASM object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o
FAILED: _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o 
/opt/rh/gcc-toolset-12/root/bin//as --defsym XXH_NAMESPACE=ZSTD_ --defsym ZSTDLIB_HIDDEN="" --defsym ZSTDLIB_VISIBLE="" -I/work/ITK-source/ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/Eigen3/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/KWSys/src -I/work/oneTBB-prefix/include -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/Core/Common -I/work/ITK-source/ITK/Modules/Core/Common/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/IO/ImageBase -I/work/ITK-source/ITK/Modules/IO/ImageBase/include -I/work/ITK-source/ITK/Modules/IO/HDF5/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I/work/ITK-source/ITK/Modules/ThirdParty/ZLIB/src -I/work/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build/lib -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib -O3 -DNDEBUG -fPIC -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/common --MD _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o.d -o _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -c /work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/decompress/huf_decompress_amd64.S
/opt/rh/gcc-toolset-12/root/bin//as: invalid option -- 'N'
[814/2057] Building C object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress.c.o
[815/2057] Building C object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/compress/zstd_lazy.c.o
ninja: build stopped: subcommand failed.
  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 551, in setup
```
The full build log is [here](https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3597835244/jobs/6060007750). This is somewhat a continuation of #65.

**Comment by laramiel** [comment]
I think that we want CMake to use CC for the assembler.  We may need to add something like:

`set_property(SOURCE huf_decompress_amd64.S APPEND PROPERTY COMPILE_OPTIONS "-x" "assembler-with-cpp")`

**Comment by laramiel** [comment]
You might try adding this line:

SET(ASM_OPTIONS "-x assembler-with-cpp")
SET(CMAKE_ASM_FLAGS "${CFLAGS} ${ASM_OPTIONS}" )

**Comment by dzenanz** [comment]
I have seen your edit just now. Adding
```cmake
SET(ASM_OPTIONS "-x assembler-with-cpp")
SET(CMAKE_ASM_FLAGS "${CFLAGS} ${ASM_OPTIONS}" )
```
before and after `FetchContent` calls in my code did not fix it. I will now try adding updated suggestion to `.bzl` file.

**Comment by laramiel** [comment]
The above suggestion will do basically the same thing you attempted.
Ok, if you sync my latest commit, you could try this:

Add the following code to (inside the `not header_only` condition):
 https://github.com/google/tensorstore/blob/5f189a84e7a54b8964d8cf5bf9a4dd3ecfd59450/tools/cmake/bazel_to_cmake/emit_cc.py#L192

    for f in cc_srcs:
      if f.endswith(".s") or f.endswith(".S"):
        _builder.addtext(
            f"""set_property(SOURCE {quote(f)} APPEND PROPERTY COMPILE_OPTIONS "-x" "assembler-with-cpp")\n"""
        )

**Comment by dzenanz** [comment]
Full log: https://open.cdash.org/build/8316867/configure

**Comment by dzenanz** [comment]
Changing the offending line into `f"""set_property(SOURCE "{f}" APPEND PROPERTY COMPILE_OPTIONS "-x" "assembler-with-cpp")\n""")` gets me past that error.

**Comment by dzenanz** [comment]
Build is in progress right now: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3624368376/jobs/6111273285.

**Comment by laramiel** [comment]
That still has the yasm/nasm error.

**Comment by dzenanz** [comment]
I see that now. In updating other things I managed to regress the version of docker image. I just pushed an update. The new progress is here: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3624503022/jobs/6111552269.

**Comment by laramiel** [comment]
Ok, that doesn't solve it.  Perhaps try adding another line:
```
_builder.addtext(
f"""set_property(SOURCE "{f}" PROPERTY LANGUAGE ASM)
set_property(SOURCE "{f}" APPEND PROPERTY COMPILE_OPTIONS "-x" "assembler-with-cpp")
""")
```

**Comment by dzenanz** [comment]
Trying it, status here: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3624503022/jobs/6111867176.

**Comment by laramiel** [comment]
It may just be that we're missing the proper language target.  Maybe all we need is to edit `third_party/net_zlib/workspace.bzl` and add:

`cmake_languages = ["C", "ASM"],`

**Comment by dzenanz** [comment]
But isn't the error message complaining about compiling `zstd`? Are you sure we need to focus on `zlib`?

**Comment by dzenanz** [comment]
The new build is in progress: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3624767759/jobs/6112097306.

**Comment by dzenanz** [comment]
I am retrying with `cmake_languages = ["C", "ASM"],` in `zstd`. New progress at: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3624767759/jobs/6112413590.

**Comment by laramiel** [comment]
Still getting /bin/as. Another thing to try In the net_zlib workspace.bzl file, add the prefix as:

  `prefix = "SET(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})"`

**Comment by dzenanz** [comment]
Trying it. The new status is here: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3630535593/jobs/6123993672.

**Comment by dzenanz** [comment]
It turns out I forgot a comma. Retrying: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3631227206/jobs/6125579120.

**Comment by dzenanz** [comment]
It still looks like the same error: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3631227206/jobs/6125579322

**Comment by dzenanz** [comment]
I tried using GCC-11, and declaring language together with CMake project specification: `project(IOOMEZarrNGFF CXX C ASM)`. Neither helped: https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3631789807/jobs/6126862437.

**Comment by dzenanz** [comment]
What would be the best way to disable ZSTD from building? From CMake GUI I see just a few related options: Zstd_DIR, TENSORSTORE_USE_SYSTEM_ZSTD, FETCHCONTENT_SOURCE_DIR_ZSTD, FETCHCONTENT_UPDATES_DISCONNECTED_ZSTD. Is there an easy way to disable it, or do I have to modify TensorStore's build system to accomplish that?

**Comment by laramiel** [comment]
Use `TENSORSTORE_USE_SYSTEM_ZSTD`, which will fall back to cmake's `find_package()` call.

**Comment by laramiel** [comment]
Looking at this again, perhaps I've been attacking the problem from the wrong angle. I think that I need to figure out  how the `-DNDEBUG` was added to the command line instead of trying to force CMake to use the C preprocessor.  The overall command is building in release mode, so it seems like adding the flags to c++ makes sense; so why are they in there?

```
/opt/python/cp38-cp38/bin/python setup.py bdist_wheel --build-type Release -G Ninja -- -DITK_DIR:PATH=/work/ITK-cp38-cp38-manylinux_2_28_x64 -DITK_USE_SYSTEM_SWIG:BOOL=ON -DWRAP_ITK_INSTALL_COMPONENT_IDENTIFIER:STRING=PythonWheel -DSWIG_EXECUTABLE:FILEPATH=/work/ITK-cp38-cp38-manylinux_2_28_x64/Wrapping/Generators/SwigInterface/swig/bin/swig -DCMAKE_CXX_COMPILER_TARGET:STRING=x86_64-linux-gnu -DCMAKE_INSTALL_LIBDIR:STRING=lib -DBUILD_TESTING:BOOL=OFF -DPython3_EXECUTABLE:FILEPATH=/opt/python/cp38-cp38/bin/python -DPython3_INCLUDE_DIR:PATH=/opt/python/cp38-cp38/bin/../include/python3.8
```

From your cmake build directory, is it possible to get `_deps/zstd-build/build_rules.cmake`? That would let me see  if the target `Zstd_zstdlib` has had these flags added, or if it's at a higher level in the CMakeLists.txt file.

**Comment by laramiel** [comment]
Thanks. The failed build still has `-DNDEBUG` and it doesn't appear in the build_rules.cmake file. So that means that it's set elsewhere.  Can you look for NDEBUG in the `bazel_to_cmake_vars.json` file (which is basically a dump of all the cmake variables set when the tensorstore CMake begins?   For reference, on my machine I see these lines:

```
$ grep NDEBUG *.json
"CMAKE_CXX_FLAGS_MINSIZEREL":"-Os -DNDEBUG",
"CMAKE_CXX_FLAGS_MINSIZEREL_INIT":" -Os -DNDEBUG",
"CMAKE_CXX_FLAGS_RELEASE":"-O3 -DNDEBUG",
"CMAKE_CXX_FLAGS_RELEASE_INIT":" -O3 -DNDEBUG",
"CMAKE_CXX_FLAGS_RELWITHDEBINFO":"-O2 -g -DNDEBUG",
"CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT":" -O2 -g -DNDEBUG",
```

**Comment by dzenanz** [comment]
Trying to pretty-print this file so I can extract relevant part fails in Notepad++:
```log
---------------------------
Error while trying to parse JSON
---------------------------
Could not parse the document because of error
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at JSON_Tools.JSON_Tools.JsonParser.ParseObject(String inp)
   at JSON_Tools.JSON_Tools.JsonParser.ParseSomething(String inp)
   at JSON_Tools.JSON_Tools.JsonParser.Parse(String inp)
   at Kbg.NppPluginNET.Main.TryParseJson(Boolean is_json_lines)
---------------------------
OK   
---------------------------
```
So I attach the whole file: [bazel_to_cmake_vars.zip](https://github.com/google/tensorstore/files/10187630/bazel_to_cmake_vars.zip)

**Comment by dzenanz** [comment]
There are 12 hits for `NDEBUG` in that file, in 2 groups.

**Comment by laramiel** [comment]
```
"CMAKE_CXX_FLAGS_MINSIZEREL":"-Os -DNDEBUG",
"CMAKE_CXX_FLAGS_MINSIZEREL_INIT":" -Os -DNDEBUG",
"CMAKE_CXX_FLAGS_RELEASE":"-O3 -DNDEBUG",
"CMAKE_CXX_FLAGS_RELEASE_INIT":" -O3 -DNDEBUG",
"CMAKE_CXX_FLAGS_RELWITHDEBINFO":"-O2 -g -DNDEBUG",
"CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT":" -O2 -g -DNDEBUG",

"CMAKE_C_FLAGS_MINSIZEREL":"-Os -DNDEBUG",
"CMAKE_C_FLAGS_MINSIZEREL_INIT":" -Os -DNDEBUG",
"CMAKE_C_FLAGS_RELEASE":"-O3 -DNDEBUG",
"CMAKE_C_FLAGS_RELEASE_INIT":" -O3 -DNDEBUG",
"CMAKE_C_FLAGS_RELWITHDEBINFO":"-O2 -g -DNDEBUG",
"CMAKE_C_FLAGS_RELWITHDEBINFO_INIT":" -O2 -g -DNDEBUG",
```

**Comment by dzenanz** [comment]
Here it is: [build.zip](https://github.com/google/tensorstore/files/10195600/build.zip)

**Comment by laramiel** [comment]
That didn't seem to give me any hints, sorry.  As best as I can tell, right now the C_FLAGS are being added to the ASM build, but I'm not sure why that happens.

**Comment by dzenanz** [comment]
Thanks for your help so far.

> What would be the best way to disable ZSTD from building?

Do you have an answer to this [question](https://github.com/google/tensorstore/issues/69#issuecomment-1341244258) I asked above?

**Comment by laramiel** [comment]
Adding `-DTENSORSTORE_USE_SYSTEM_ZSTD=1` should do it.

**Comment by dzenanz** [comment]
Updating to latest () didn't help. Still the same [error](https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3687806872/jobs/6241850150).

**Comment by dzenanz** [comment]
I have a new [attempt](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/1bc641847d77157d4506a80204b488feb0339ad0), building zstd via fetch_content and then trying to plug that as "system" zstd to tensorstore. However this doesn't even build locally. Here is the complete configure log:
```log
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
Found Python3: C:/Program Files/Python39/python.exe (found suitable version "3.9.13", minimum required is "3.9") found components: Interpreter Development.Module Development.Embed 
Found Python3: C:/Program Files/Python39/python.exe (found suitable version "3.9.13", minimum required is "3.7") found components: Interpreter 
ITK is setting IOOMEZarrNGFF's MSVC_RUNTIME_LIBRARY to dynamic
ZSTD VERSION: 1.5.2
CMAKE_INSTALL_PREFIX: C:/Program Files/HDF_Group/HDF5/1.12.2
CMAKE_INSTALL_LIBDIR: lib
ZSTD_LEGACY_SUPPORT not defined!
ZSTD_MULTITHREAD_SUPPORT is disabled
CMake Deprecation Warning at src/CMakeLists.txt:46 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Zstd_LIBRARY == C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/hdf5-build/bin/$(Configuration)/zstd_static.lib
Found Python3: C:/Program Files/Python39/python.exe (found version "3.9.13") found components: Interpreter 
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Zstd (missing: Zstd_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/tensorstore-src/tools/cmake/FindZstd.cmake:35 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/blosc-build/build_rules.cmake:45 (find_package)
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/blosc-src/CMakeLists.txt:35 (include)


Configuring incomplete, errors occurred!
See also "C:/Dev/ITKIOOMEZarrNGFF-vs19/CMakeFiles/CMakeOutput.log".
See also "C:/Dev/ITKIOOMEZarrNGFF-vs19/CMakeFiles/CMakeError.log".
```
When I was doing an incremental build, `C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/hdf5-build/bin/$(Configuration)/zstd_static.lib` existed (for both Debug and RelWithDebInfo configurations), and the error occurred later on in the configure process, complaining that it could not find `Zstd_LIBRARY`.

**Comment by dzenanz** [comment]
Any suggestions?

**Comment by jbms** [comment]
If you want to use zstd via FetchContent you should not specify `TENSORSTORE_USE_SYSTEM_ZSTD; that expects to find an existing zstd library at configure time, but with FetchContent the library won't yet be built --- instead it should be sufficient to call `FetchContent` before the tensorstore build gets loaded (via FetchContent_MakeAvailable), since the first FetchContent call for a given package name takes precedence in CMake.
Additionally you will need to define a `Zstd::Zstd` alias target.

It is our intention that this should work (substituting your own build of a cmake package that tensorstore depends on), but we haven't tested it.

It would be great to figure out what the issue is with our zstd build, though.  Probably trying to find a minimal standalone CMakeLists.txt that reproduces the issue on manylinux_2_28_x64 would be very helpful in getting to the bottom of it.

**Comment by dzenanz** [comment]
[Changing](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/11c91141fb84886a73005d7e4eb3fc06a1eec27a) according to this advice results in:
```log
...
ZSTD VERSION: 1.5.2
CMAKE_INSTALL_PREFIX: C:/Program Files/HDF_Group/HDF5/1.12.2
CMAKE_INSTALL_LIBDIR: lib
ZSTD_LEGACY_SUPPORT not defined!
ZSTD_MULTITHREAD_SUPPORT is disabled
CMake Error at C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/zstd_lib-build/zstdConfig.cmake:1 (include):
  include could not find requested file:

    C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/zstd_lib-build/zstdTargets.cmake
Call Stack (most recent call first):
  src/CMakeLists.txt:44 (find_package)


Found Python3: C:/Program Files/Python39/python.exe (found version "3.9.13") found components: Interpreter 
CMake Error at C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/zstd-build/build_rules.cmake:84 (add_library):
  add_library cannot create ALIAS target "Zstd::Zstd" because another target
  with the same name already exists.
Call Stack (most recent call first):
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/zstd-src/CMakeLists.txt:35 (include)
```
Indeed, `zstdTargets.cmake` does not exist at configure time.

If I uncomment `set(TENSORSTORE_USE_SYSTEM_ZSTD ON)`, then the error is quite similar to before (with the addition of complaint for `zstdTargets.cmake`).

**Comment by dzenanz** [comment]
> reproduces the issue on manylinux_2_28_x64

Is there a way to rip out just `zstd`? It would make testing easier. Looking at `C:\Dev\ITKIOOMEZarrNGFF-vs19\_deps\zstd-src\CMakeLists.txt`, it contains full paths such as `C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/tensorstore-src/tools/cmake/bazel_to_cmake.py`.

**Comment by laramiel** [comment]
You could try starting by just adding this to your base `CMakeLists.txt` before tensorstore:
```
FetchContent_Declare(Zstd
    URL "https://github.com/facebook/zstd/archive/v1.5.2.zip"
    URL_HASH "SHA256=53f4696f3cec8703f12d3402707a6aaf7eb92d43c90d61e1d32454bda5da7b9c")

FetchContent_MakeAvailable(Zstd)

set(TENSORSTORE_USE_SYSTEM_ZSTD ON)

```

**Comment by laramiel** [comment]
As for ripping out ZSTD, we don't really have a built-in option to do that; it's linked into litiff and blosc.

So you could, perhaps, remove it from `libtiff.BUILD.bazel` and change the `ZSTD_SUPPORT=1` define there, also remove it from `org_blosc_cblosc/bundled.BUILD.bazel` as well.

**Comment by dzenanz** [comment]
Applying [the first suggestion](https://github.com/google/tensorstore/issues/69#issuecomment-1354022425) (commit [here](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/fb93c94cce5f06ffe0d917e94185f6b232287e58)) yields a very similar error to before:
```log
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
Found Python3: C:/Program Files/Python39/python.exe (found suitable version "3.9.13", minimum required is "3.9") found components: Interpreter Development.Module Development.Embed 
Found Python3: C:/Program Files/Python39/python.exe (found suitable version "3.9.13", minimum required is "3.7") found components: Interpreter 
ITK is setting IOOMEZarrNGFF's MSVC_RUNTIME_LIBRARY to dynamic
Found Python3: C:/Program Files/Python39/python.exe (found version "3.9.13") found components: Interpreter 
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Zstd (missing: Zstd_LIBRARY Zstd_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/tensorstore-src/tools/cmake/FindZstd.cmake:35 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/blosc-build/build_rules.cmake:45 (find_package)
  C:/Dev/ITKIOOMEZarrNGFF-vs19/_deps/blosc-src/CMakeLists.txt:35 (include)
```

**Comment by dzenanz** [comment]
Trying to [build zstd during configure](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/1f3261db5e62a9ed33d95d769fa8597d70e25390) causes some infinite recursion:
```log
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
Found Python3: C:/Program Files/Python39/python.exe (found suitable version "3.9.13", minimum required is "3.9") found components: Interpreter Development.Module Development.Embed 
Found Python3: C:/Program Files/Python39/python.exe (found suitable version "3.9.13", minimum required is "3.7") found components: Interpreter 
ITK is setting IOOMEZarrNGFF's MSVC_RUNTIME_LIBRARY to dynamic
ZSTD VERSION: 1.5.2
CMAKE_INSTALL_PREFIX: C:/Program Files/HDF_Group/HDF5/1.12.2
CMAKE_INSTALL_LIBDIR: lib
ZSTD_LEGACY_SUPPORT not defined!
ZSTD_MULTITHREAD_SUPPORT is disabled
Building zstd
Building zstd


Building zstd


Building zstd


Building zstd


Building zstd


Building zstd
```

**Comment by dzenanz** [comment]
@laramiel any further suggestions?

**Comment by jbms** [comment]
I think it might help to compare the compile commands issued for zstd between manylinux2 and a working Linux configuration.

I suspect something is going wrong with the CMake asm compiler configuration.

**Comment by dzenanz** [comment]
Here is the failing command:
`/opt/rh/gcc-toolset-12/root/bin//as --defsym XXH_NAMESPACE=ZSTD_ --defsym ZSTDLIB_HIDDEN="" --defsym ZSTDLIB_VISIBLE="" -I/work/ITK-source/ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/Eigen3/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/KWSys/src -I/work/oneTBB-prefix/include -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/Core/Common -I/work/ITK-source/ITK/Modules/Core/Common/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/IO/ImageBase -I/work/ITK-source/ITK/Modules/IO/ImageBase/include -I/work/ITK-source/ITK/Modules/IO/HDF5/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I/work/ITK-source/ITK/Modules/ThirdParty/ZLIB/src -I/work/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build/lib -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib -O3 -DNDEBUG -fPIC -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/common --MD _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o.d -o _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -c /work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/decompress/huf_decompress_amd64.S`

and successful command:
`/usr/bin/cc -DXXH_NAMESPACE=ZSTD_ -DZSTDLIB_HIDDEN="" -DZSTDLIB_VISIBLE="" -I/home/dzenan/ITK-git/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/Eigen3/src -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/KWSys/src -I/home/dzenan/ITK-git/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/home/dzenan/ITK-git/Modules/ThirdParty/VNL/src/vxl/vcl -I/home/dzenan/ITK-git/Modules/ThirdParty/VNL/src/vxl/core -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/VNL/src/vxl/vcl -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/VNL/src/vxl/core -I/home/dzenan/ITK-git-rel/Modules/Core/Common -I/home/dzenan/ITK-git/Modules/Core/Common/include -I/home/dzenan/ITK-git-rel/Modules/IO/ImageBase -I/home/dzenan/ITK-git/Modules/IO/ImageBase/include -I/home/dzenan/ITK-git/Modules/IO/HDF5/include -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/ZLIB/src -I/home/dzenan/ITK-git-rel/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I/home/dzenan/ITK-git/Modules/ThirdParty/ZLIB/src -I/home/dzenan/ITKIOOMEZarrNGFF/include -I/home/dzenan/ITKIOOMEZarrNGFF-rwdi/include -I/home/dzenan/ITKIOOMEZarrNGFF-rwdi/_deps/zstd-build -I/home/dzenan/ITKIOOMEZarrNGFF-rwdi/_deps/zstd-build/lib -I/home/dzenan/ITKIOOMEZarrNGFF-rwdi/_deps/zstd-src -I/home/dzenan/ITKIOOMEZarrNGFF-rwdi/_deps/zstd-src/lib -O2 -g -DNDEBUG -fPIC -I/home/dzenan/ITKIOOMEZarrNGFF-rwdi/_deps/zstd-src/lib/common -MD -MT _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -MF _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o.d -o _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -c /home/dzenan/ITKIOOMEZarrNGFF-rwdi/_deps/zstd-src/lib/decompress/huf_decompress_amd64.S`.

**Comment by dzenanz** [comment]
So you are right, that the trick is that `cc` should be invoked to compile it, and not `as`. Which just brings us back to how.

**Comment by jbms** [comment]
The issue seems to be that in your build, CMake is detecting the assembler as "Found assembler: /opt/rh/gcc-toolset-12/root/bin//as" while for a working build it needs to use "/opt/rh/gcc-toolset-12/root/bin//cc" instead.

I believe that normally CMake will attempt to use the C compiler for assembly by default, but for some reason that is not happening here.

I tried to reproduce that with a very simple CMakeLists.txt running in the manylinux_2_28_x86_64 docker image, but could not --- the assembler was always detected as "/opt/rh/gcc-toolset-12/root/bin//cc".

If you change your build to specify `--debug-output --trace-expand` as additional options to CMake, that might help in figuring out why `as` is being detected instead of `cc`.

In the past I have observed unusual behavior if all of the `enable_language` calls don't happen at the top level, but I am not sure if that is related to the issue here.  But you could try adding:

```
enable_language(C)
enable_language(CXX)
enable_language(ASM_NASM)
enable_language(ASM)
```

to your top-level CMakeLists.txt.

**Comment by dzenanz** [comment]
@thewtex suggested that assembler choice is probably coming from [toolchain](https://github.com/dockcross/dockcross/blob/e913a7f1d632940a4e6fb233fb6b5cdfa8c4502d/manylinux_2_28-x64/Toolchain.cmake#L11) being used for package building. So I tried overriding it in [my code](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/22ec23cb22c2d0415622d57558bbfdf63da63223). That works, but it only produces a [different error](https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3789759919/jobs/6443815026):
```log
[813/2055] Building ASM object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o
FAILED: _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o 
/opt/rh/gcc-toolset-11/root/bin//gcc --defsym XXH_NAMESPACE=ZSTD_ --defsym ZSTDLIB_HIDDEN="" --defsym ZSTDLIB_VISIBLE="" -I/work/ITK-source/ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/Eigen3/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/KWSys/src -I/work/oneTBB-prefix/include -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/Core/Common -I/work/ITK-source/ITK/Modules/Core/Common/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/IO/ImageBase -I/work/ITK-source/ITK/Modules/IO/ImageBase/include -I/work/ITK-source/ITK/Modules/IO/HDF5/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I/work/ITK-source/ITK/Modules/ThirdParty/ZLIB/src -I/work/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build/lib -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib -O3 -DNDEBUG -fPIC -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/common --MD _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o.d -o _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -c /work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/decompress/huf_decompress_amd64.S
gcc: error: unrecognized command-line option ‘--defsym’
gcc: error: unrecognized command-line option ‘--defsym’
gcc: error: unrecognized command-line option ‘--defsym’
gcc: error: unrecognized command-line option ‘--MD’; did you mean ‘-MD’?
```

**Comment by dzenanz** [comment]
@jbms Just setting the [4 languages](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/5e1dfc62832863babe024475689027183dba8083) makes [no difference](https://github.com/dzenanz/ITKIOOMEZarrNGFF/actions/runs/3789896780/jobs/6444069589), I still get `/opt/rh/gcc-toolset-11/root/bin//as: invalid option -- 'N'`.

**Comment by jbms** [comment]
Okay, looks like the issue is indeed the toolchain file.  I think it is a bug to specify `CMAKE_ASM_COMPILER=as` in the toolchain file, because that prevents compiling asm sources that require the C preprocessor (typically such sources use a ".S" extension).

Unfortunately I think the way you are attempting to override `CMAKE_ASM_COMPILER` does not work --- CMake has already run its compiler detection logic (which appears to check if the asm compiler basename is "as") and determined that it should use "--defsym" rather than "-D", "--MD" instead of "-MD", etc.  I'm not sure if there is a way to override the toolchain file --- instead you may just need to modify the toolchain file.

**Comment by dzenanz** [comment]
Trying to [unset CMAKE_ASM_COMPILER](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/f91692759daa6c4b108dd96d15b0939453e3e2ce) within my code does not work, with the same error as before:
```log
[1023/2055] Building ASM object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o
FAILED: _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o 
/opt/rh/gcc-toolset-11/root/bin//as --defsym XXH_NAMESPACE=ZSTD_ --defsym ZSTDLIB_HIDDEN="" --defsym ZSTDLIB_VISIBLE="" -I/work/ITK-source/ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/Eigen3/src -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/KWSys/src -I/work/oneTBB-prefix/include -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/Core/Common -I/work/ITK-source/ITK/Modules/Core/Common/include -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/IO/ImageBase -I/work/ITK-source/ITK/Modules/IO/ImageBase/include -I/work/ITK-sourc...
/opt/rh/gcc-toolset-11/root/bin//as: invalid option -- 'N'
```
Inspired by [relevant CMake code](https://gitlab.kitware.com/cmake/cmake/blob/v3.24.2/Modules/CMakeDetermineASMCompiler.cmake), trying to set [both CMAKE_ASM_COMPILER and CMAKE_ASM_COMPILER_ID](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/566eae3fbdf01c201526938f0234230a39275edf) does not work either, with the same error message as before:
```log
[1023/2055] Building ASM object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o
FAILED: _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o 
/opt/rh/gcc-toolset-11/root/bin//gcc --defsym XXH_NAMESPACE=ZSTD_ --defsym ZSTDLIB_HIDDEN="" --defsym ZSTDLIB_VISIBLE="" -I/work/ITK-source/ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/Eigen3/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/KWSys/src -I/work/oneTBB-prefix/include -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/Core/Common -I/work/ITK-source/ITK/Modules/Core/Common/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/IO/ImageBase -I/work/ITK-source/ITK/Modules/IO/ImageBase/include -I/work/ITK-source/ITK/Modules/IO/HDF5/include -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src -I/work/ITK-cp38-cp38-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I/work/ITK-source/ITK/Modules/ThirdParty/ZLIB/src -I/work/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/include -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-build/lib -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib -O3 -DNDEBUG -fPIC -I/work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/common --MD _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o.d -o _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -c /work/_skbuild/linux-x86_64-3.8/cmake-build/_deps/zstd-src/lib/decompress/huf_decompress_amd64.S
gcc: error: unrecognized command-line option ‘--defsym’
gcc: error: unrecognized command-line option ‘--defsym’
gcc: error: unrecognized command-line option ‘--defsym’
gcc: error: unrecognized command-line option ‘--MD’; did you mean ‘-MD’?
```
I will try modifying the toolchain file next.

**Comment by dzenanz** [comment]
I tried some testing today (https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/issues/13). No success so far.

**Comment by dzenanz** [comment]
Removing AS from CMake toolchain file and environment variables [seems to do the trick](https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/issues/13#issuecomment-1371414858).

**Comment by dzenanz** [comment]
@laramiel @jbms thank you both!
